camunda.bpm:
  database:
    type: postgres
  admin-user:
    id: demo
    password: demo
    firstName: Demo
  filter:
    create: All tasks
  job-execution:
    deployment-aware: true
com:
  camunda:
    datasource:
      jdbc-url: jdbc:postgresql://tai.db.elephantsql.com/iopavwsd
      username: iopavwsd
      password: lngjeABwrAJUalOkkH_DLFxc_b1Uwatm
      driverClassName: org.postgresql.Driver
      poolName: camunda-pool
